version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    # command: --storage-driver=overlay2
    labels:
      com.example.description: "Jenkins Server by Ye Win"
    ports: 
      - "9000:8080"
      - "50000:50000"
    networks:
      jenkins:
        aliases: 
          - docker
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
     
volumes: 
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  jenkins:
    driver: bridge
    name: jenkins