version: "3.9"

services:
  jenkins:
    #image: jenkins/jenkins:lts-alpine
    # I don't run image with above and I get jenkins image with Dockerfile and build that file with below build . command
    # (you can reference to my Dockerfile for jenkins image)
    build: .
    container_name: jenkins
    #command: /bin/sh -c "jenkins.sh"
    # add user to group with uid and gid
    #user: 1000:10001
    restart: unless-stopped
    #privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    labels:
      com.example.description: "Jenkins Server by Ye Win"
    ports: 
      - "9000:8080"
      - "50000:50000"
    networks:
      # Here, I run my db as this way -> https://github.com/yewin-mm/mysql-docker-container
      # So, I need to join my MySQL container network to access my db from application for unit testing and accessing to my local db
      # if you run MySQL db with container and gave network name not like me, 
      # you need to add your network name instead of below -mysql and you need to change that name in below network section.
      - mysql

      # if you don't run DB inside docker container like run with installer file,
      # you need to uncomment below jenkins, aliases and docker tags and comment out above -mysql tag, 
      # also you need to uncomment jenkins network below network section.

      #jenkins:
        #aliases: 
          #- docker
      
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client


      # Below is bind mount with jenkins to your host docker daemon, 
      # but it has security risk and so I installed docker cli in my jenkins server with dockerfile. (you can reference to my Dockerfile)

      # bind with docker sock and jenkins to enable docker command in jenkins 
      # it's not recommend option as it's difficult to maintain and less security, 
      # it's better using to build image with Kaniko project together with kubernetes than binding with docker socket in jenkins
      # but here, I used traditional method to use docker command in jenkins as sample. So, I mount with docker sock.

      # bind with your docker installation directory
      #- /usr/bin/docker:/usr/bin/docker
      # bind with docker sock binary directory
      #- /var/run/docker.sock:/var/run/docker.sock

    # set timezone to Myanmar
    # you can set your country timezone, can see full zone id here (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
    environment:
      - TZ=Asia/Yangon
     
volumes: 
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  # Here, I run my db as this way -> https://github.com/yewin-mm/mysql-docker-container
  # So, I need to join my MySQL container network to access my db from application for unit testing.
  # if you run MySQL db with container and gave network name not like me, 
  # you need to add your network name instead of below -mysql and you need to change that name in below network section.
  mysql:
    external: true

  # if you don't run DB inside docker container like run with installer file,
  # you need to uncomment below jenkins, driver and name and comment out above mysql and external tags
  
  #jenkins:
    #driver: bridge
    #name: jenkins
  