version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    # command: --storage-driver=overlay2
    labels:
      com.example.description: "Jenkins Server by Ye Win"
    ports: 
      - "9000:8080"
      - "50000:50000"
    networks:
      # if you run your db as container like this ways https://github.com/yewin-mm/mysql-docker-container
      # you need comment out below jenkins, aliases and docker. And also need to comment out in below networks section
      jenkins:
        aliases: 
          - docker
      # uncomment below mysql if you run your db as container. And also need to uncomment in below networks section
      # - mysql
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
     
volumes: 
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  # if you run your db as container like this ways https://github.com/yewin-mm/mysql-docker-container
  # you need comment out below jenkins, driver and name
  jenkins:
    driver: bridge
    name: jenkins
  # uncomment below mysql and external if you run your db as container. (add your db container network)
  # mysql:
    # external: true