version: "3.9"

services:
  jenkins:
    #image: jenkins/jenkins:lts-alpine
    # I don't run image with above and I get jenkins image with Dockerfile and build that file with below build . command
    # (you can reference to my Dockerfile for jenkins image)
    build: .
    container_name: jenkins
    # user: jenkins
    # user: root
    # add user to group with uid and gid (I don't need this step as it's already in dockerfile)
    # user: "1001:1001"
    restart: unless-stopped
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
      # - DOCKER_HOST=unix:///var/run/docker.sock
    labels:
      com.example.description: "Jenkins Server by Ye Win"
    ports: 
      - "9000:8080"
      - "50000:50000"
    networks:
      # Here, I run my db as this way -> https://github.com/yewin-mm/mysql-docker-container
      # So, I need to join my MySQL container network to access my db from application for unit testing and accessing to my local db
      # if you run MySQL db with container and gave network name not like me, 
      # you need to add your network name instead of below -mysql and you need to change that name in below network section.
      - mysql

      # if you don't run DB inside docker container like run with installer file,
      # you need to uncomment below jenkins, aliases and docker tags and comment out above -mysql tag, 
      # also you need to uncomment jenkins network below network section.

      #jenkins:
        #aliases: 
          #- docker
      
    # volume is to store jenkins data 
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

      # bind with docker sock and jenkins to enable docker action in jenkins 
      # it's not recommend option as it's difficult to maintain and less security, 
      # it's better using to build image with Kaniko project together with kubernetes than binding with docker socket in jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      
    # group_add:
      # - docker
    # command: sh -c "chgrp docker /var/run/docker.sock && jenkins.sh"
    # command: sh -c "chmod 660 /var/run/docker.sock"
    # command: sh -c "/script.sh && exec myexecutable"
      

    # set timezone to Myanmar
    # you can set your country timezone, can see full zone id here (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
    environment:
      - TZ=Asia/Yangon


volumes: 
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  # Here, I run my db as this way -> https://github.com/yewin-mm/mysql-docker-container
  # So, I need to join my MySQL container network which in in external container to access my db from application for unit testing running.
  # if you run MySQL db with container and gave network name not like me,   
  mysql:
    external: true

  # if you don't run DB inside docker container like run with installer file,
  # you need to uncomment below jenkins, driver and name and comment out above mysql and external tags
  
  #jenkins:
    #driver: bridge
    #name: jenkins

